### ISSUE TITLE
awesome project!

### ISSUE THREAD

**Issue by DTrejo** [bigredwill/notational-markdown#1]
Just stumbled across this - i should definitely try this when I have a moment. The feature I'd contribute, if any: 1-click publishing to my blog/wherever, straight from NV/NM. And then also allow myself to edit it and republish.

Great stuff :)

PS I bet you could charge $5/mo to back up notes for people.

**Comment by bigredwill** [comment]
Thank you! It's still very, very basic at the moment.  

Right now the goal is to be able to take notes in Markdown quickly and easily, but that's the direction I am thinking for the project 👍

**Comment by DTrejo** [comment]
It's all good we can close this, i know how annoying unclosed issues are :)
